config/routes.rb
TailoredRepublic::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

  devise_for :users, skip: [:sessions, :registrations],
             controllers: { sessions: :sessions, registrations: :registrations }
  as :user do
    get 'login' => 'sessions#new', :as => :new_user_session
    post 'login' => 'sessions#create', :as => :user_session
    delete 'sign-out' => 'sessions#destroy', :as => :destroy_user_session
    post 'account' => 'registrations#create', :as => :user_registration
    put 'account' => 'registrations#update'
    delete 'account' => 'devise/registrations#destroy'
    get 'account' => 'registrations#edit', :as => :edit_user_registration
  end

  resources :users, only: [:show, :update, :destroy, :index, :edit], path: '/admin/users'
  resources :customizations, only: [:show, :create, :update]
  resource  :cart, only: [:show]
  resource  :measurements, only: [:show, :create, :update]
  resources :products, only: [:show, :index, :create, :update] do
    resources :reviews, only: [:new, :edit] do
      collection do
        get 'paginated'
      end
    end
  end
  resources :products, only: [:new, :edit, :admin_index], path: '/admin/products' do
    collection do
      get 'index', action: 'admin_index'
    end
  end
  resources :coupons, except: [:show], path: '/admin/coupons' do
    collection do
      get 'help'
    end
  end
  resources :line_items, path: '/line-items', only: [:create, :destroy, :update]
  resources :tape_measure_requests, only: [:index, :update], path: '/admin/tape-measure-requests'
  resources :tape_measure_requests, only: [:new, :create], path: '/tape-measure-requests' do
    collection do
      get 'thank_you', path: 'thank-you'
    end
  end
  resources :orders, only: [:admin_index, :show], path: '/admin/orders' do
    collection do
      get 'index', action: 'admin_index'
    end
  end
  resources :orders, only: [:new, :create, :index] do
    collection do
      post 'review'
      post 'new', path: 'new'
      get 'thank_you', path: 'thank-you'
    end
  end
  resources :referrals, only: [:index] do
    collection do
      get 'invite/:referral_code', :action => 'invite'
      post 'email-friends', :action => 'email_friends'
    end
  end
  resources :reviews, only: [:update, :create, :index]
  resources :reviews, only: [:admin_index], path: '/admin/reviews' do
    collection do
      get 'index', action: 'admin_index'
    end
  end
  resources :testimonials, only: [:index, :update, :create]
  resources :testimonials, except: [:index, :update, :create], path: '/admin/testimonials' do
    collection do
      get 'index', action: 'admin_index'
    end
  end

  match '/shop/:category' => 'shop#index'
  match '/shop/:category/:subcategory' => 'shop#index'
  match '/gift-cards' => 'shop#gift_cards', :as => 'gift_cards'
  match '/shop' => 'shop#index'
  match '/home' => 'home#index'
  match '/measurements/:initial_slide' => 'measurements#show'
  match '/subscribe-to-newsletter' => 'mailing_list#subscribe', :as => 'subscribe_to_newsletter'
  match '/about' => 'pages#about'
  match '/admin' => 'pages#admin'
  match '/faq' => 'pages#faq'
  match '/graduation-1' => 'pages#graduation_with_clickable_product'
  match '/graduation-2' => 'pages#graduation_without_clickable_product'
  match '/lookbook' => 'pages#lookbook'
  match '/partners' => 'pages#partners'
  match '/press' => 'pages#press'
  match '/privacy-policy' => 'pages#privacy_policy'
  match '/process' => 'pages#process'
  match '/team' => 'pages#team'
  match '/terms-of-service' => 'pages#terms_of_service'
  match '/weddings' => 'pages#weddings'
  match '/top-picks' => 'pages#top_picks'

end

app/models/tape_measure_request.rb
class TapeMeasureRequest < ActiveRecord::Base
  before_create :set_sent_to_false
  has_one :shipping_address, as: :addressable, validate: true

  attr_accessible :email, :ip_address, :sent, :shipping_address_attributes

  validates_presence_of :email

  accepts_nested_attributes_for :shipping_address

  def self.filter_by_status(status, page)
    if status == 'all'
      self.paginate(page: page, per_page: 20, order: 'created_at DESC')
    elsif status == 'sent'
      self.paginate(page: page, per_page: 20, order: 'created_at DESC', conditions: ['sent = ?', true])
    elsif status == 'unsent'
      self.paginate(page: page, per_page: 20, order: 'created_at DESC', conditions: ['sent = ?', false])
    end
  end

  def set_sent_to_false
    self.sent = false
    true
  end
end

app/controllers/tape_measure_requests_controller.rb
class TapeMeasureRequestsController < ApplicationController
  load_and_authorize_resource only: [:index, :update]

  def index
    params[:filter] ||= 'all'
    params[:page] ||= 1
    @filter = params[:filter]
    @tape_measure_requests = TapeMeasureRequest.filter_by_status(@filter, params[:page])
  end

  def new
    @tape_measure_request = TapeMeasureRequest.new
    if user_signed_in?
       @tape_measure_request.shipping_address = current_user.shipping_address.dup unless current_user.shipping_address.blank?
       @tape_measure_request.email = current_user.email unless current_user.email.blank?
    else
      @tape_measure_request.build_shipping_address
    end

  end

  def create
    @tape_measure_request = TapeMeasureRequest.new(params[:tape_measure_request])
    @tape_measure_request.ip_address = request.remote_ip

    if @tape_measure_request.save
      if params[:subscribe_to_mailing_list] == "1"
        begin
          Gibbon.list_subscribe(id: GIBBON_LIST_ID, email_address: params[:tape_measure_request][:email])
        rescue
          puts 'Ignoring error'
        end
      end
      session[:requested_tape_measure] = true
      redirect_to :thank_you_tape_measure_requests
    else
      render :new
    end
  end

  def update
    @tape_measure_request = TapeMeasureRequest.find(params[:id])

    if @tape_measure_request.update_attributes(params[:tape_measure_request])
      head :no_content
    else
      render json: @tape_measure_request.errors, status: :unprocessable_entity
    end
  end

  def thank_you
    unless session.has_key?('requested_tape_measure')
      redirect_to :new_tape_measure_request
    end
  end
end

app/views/tape_measure_requests/index.html.erb
<div class="twelve columns">
  <h2>Tape Measure Requests</h2>
  <div class="outlined">
    <div class="six columns no-padding">
      <%= form_tag tape_measure_requests_path, method: 'get' do %>
        <%= label_tag :filter, 'Filter By Status' %>
        <%= select_tag :filter, options_for_select(['all', 'sent', 'unsent'], @filter) %>
      <% end %>
    </div>

    <table>
      <tr>
        <th>Name</th>
        <th>Line 1</th>
        <th>Line 2</th>
        <th>City</th>
        <th>State</th>
        <th>Zip</th>
        <th>Email</th>
        <th>IP Address</th>
        <th>Sent?</th>
        <th>Created At</th>
      </tr>

      <% @tape_measure_requests.each do |tape_measure_request| %>
        <tr>
          <td><%= tape_measure_request.shipping_address.name %></td>
          <td><%= tape_measure_request.shipping_address.line1 %></td>
          <td><%= tape_measure_request.shipping_address.line2 %></td>
          <td><%= tape_measure_request.shipping_address.city %></td>
          <td><%= tape_measure_request.shipping_address.state %></td>
          <td><%= tape_measure_request.shipping_address.zip %></td>
          <td><%= tape_measure_request.email %></td>
          <td><%= tape_measure_request.ip_address %></td>
          <td><%= select_tag :sent, options_for_select(['Yes', 'No'], tape_measure_request.sent ? 'Yes' : 'No'), class: 'sent-select', id: "sent_#{tape_measure_request.id}", data: { id: tape_measure_request.id } %></td>
          <td><%= tape_measure_request.created_at.in_time_zone('Pacific Time (US & Canada)') %></td>
        </tr>
      <% end %>
    </table>

    <%= will_paginate @tape_measure_requests %>
  </div>
</div>

<script>
  new TR.Views.TapeMeasureRequests();
</script>

app/views/tape_measure_requests/new.html.erb
<% title_helper('Get A Free Measuring Tape') %>

<div class="content-wrapper">
  <div class="row">
    <div class="twelve columns">
      <h2>Get a Free Measuring Tape</h2>
      <div class="outlined">
        <p class="bold">Enter your name, address, and e-mail and we will send you a free Tailored Republic measuring tape.</p>
        <% unless user_signed_in? %>
          <p class="bold">If you have an account with a shipping address, <%= link_to 'sign in to autofill your address.', new_user_session_path %> </p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="twelve columns">
      <%= form_for @tape_measure_request, url: '/tape-measure-requests', html: { class: 'outlined' } do |f| %>
        <%= render 'shared/form_errors', resource: @tape_measure_request %>
        <%= render 'addresses/nested_form', parent_form: f, address_type: :shipping_address %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <label><%= check_box_tag :subscribe_to_mailing_list, '1', true %> Subscribe me to the Tailored Republic mailing list</label>
        <%= f.submit 'Submit', class: 'button large full-width' %>
      <% end %>
    </div>
  </div>
</div>

<script>
  mixpanel.track('Viewed Request a Tape Measure Page')
</script>

app/views/tape_measure_requests/thank_you.html.erb
<% title_helper('Tape Measure - Thank You') %>

<div class="row content-wrapper">
  <h4>Thanks for requesting a tape measure!</h4>
  <div class="twelve columns outlined">
    <p>Your tape measure request has been received. You can expect a tape measure in the mail in a few days.</p>
    <%= link_to 'Go To Shop', '/shop/suits', class: 'button large full-width' %>
  </div>
</div>

<script>
  mixpanel.track('Ordered a Tape Measure');
</script>