config/routes.rb
TailoredRepublic::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

  devise_for :users, skip: [:sessions, :registrations],
             controllers: { sessions: :sessions, registrations: :registrations }
  as :user do
    get 'login' => 'sessions#new', :as => :new_user_session
    post 'login' => 'sessions#create', :as => :user_session
    delete 'sign-out' => 'sessions#destroy', :as => :destroy_user_session
    post 'account' => 'registrations#create', :as => :user_registration
    put 'account' => 'registrations#update'
    delete 'account' => 'devise/registrations#destroy'
    get 'account' => 'registrations#edit', :as => :edit_user_registration
  end

  resources :users, only: [:show, :update, :destroy, :index, :edit], path: '/admin/users'
  resources :customizations, only: [:show, :create, :update]
  resource  :cart, only: [:show]
  resource  :measurements, only: [:show, :create, :update]
  resources :products, only: [:show, :index, :create, :update] do
    resources :reviews, only: [:new, :edit] do
      collection do
        get 'paginated'
      end
    end
  end
  resources :products, only: [:new, :edit, :admin_index], path: '/admin/products' do
    collection do
      get 'index', action: 'admin_index'
    end
  end
  resources :coupons, except: [:show], path: '/admin/coupons' do
    collection do
      get 'help'
    end
  end
  resources :line_items, path: '/line-items', only: [:create, :destroy, :update]
  resources :tape_measure_requests, only: [:index, :update], path: '/admin/tape-measure-requests'
  resources :tape_measure_requests, only: [:new, :create], path: '/tape-measure-requests' do
    collection do
      get 'thank_you', path: 'thank-you'
    end
  end
  resources :orders, only: [:admin_index, :show], path: '/admin/orders' do
    collection do
      get 'index', action: 'admin_index'
    end
  end
  resources :orders, only: [:new, :create, :index] do
    collection do
      post 'review'
      post 'new', path: 'new'
      get 'thank_you', path: 'thank-you'
    end
  end
  resources :referrals, only: [:index] do
    collection do
      get 'invite/:referral_code', :action => 'invite'
      post 'email-friends', :action => 'email_friends'
    end
  end
  resources :reviews, only: [:update, :create, :index]
  resources :reviews, only: [:admin_index], path: '/admin/reviews' do
    collection do
      get 'index', action: 'admin_index'
    end
  end
  resources :testimonials, only: [:index, :update, :create]
  resources :testimonials, except: [:index, :update, :create], path: '/admin/testimonials' do
    collection do
      get 'index', action: 'admin_index'
    end
  end

  match '/shop/:category' => 'shop#index'
  match '/shop/:category/:subcategory' => 'shop#index'
  match '/gift-cards' => 'shop#gift_cards', :as => 'gift_cards'
  match '/shop' => 'shop#index'
  match '/home' => 'home#index'
  match '/measurements/:initial_slide' => 'measurements#show'
  match '/subscribe-to-newsletter' => 'mailing_list#subscribe', :as => 'subscribe_to_newsletter'
  match '/about' => 'pages#about'
  match '/admin' => 'pages#admin'
  match '/faq' => 'pages#faq'
  match '/graduation-1' => 'pages#graduation_with_clickable_product'
  match '/graduation-2' => 'pages#graduation_without_clickable_product'
  match '/lookbook' => 'pages#lookbook'
  match '/partners' => 'pages#partners'
  match '/press' => 'pages#press'
  match '/privacy-policy' => 'pages#privacy_policy'
  match '/process' => 'pages#process'
  match '/team' => 'pages#team'
  match '/terms-of-service' => 'pages#terms_of_service'
  match '/weddings' => 'pages#weddings'
  match '/top-picks' => 'pages#top_picks'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  belongs_to :user
  delegate :empty?, to: :line_items

  def num_items
    line_items.length
  end

  def total_price
    if empty?
      0
    else
      LineItem.sum_price(line_items)
    end
  end

  def only_shirts?
    LineItem.only_shirts?(line_items)
  end

  def line_items_light
    line_items.map do |l|
      { id: l.id, total_price: l.total_price, quantity: l.quantity, unit_price: l.unit_price, category: l.category }
    end
  end

  # Can skip measurements if there are no suits or shirts in the cart
  def skip_measurements?
    !line_items.any? { |l| l.product.category == :suit || l.product.category == :shirt }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @line_items = @cart.line_items_light
    @skip_measurements = @cart.skip_measurements?
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def customization_to_key(customization)
    customization.downcase.tr(" ", "_")
  end
end

app/views/carts/_checkout.html.erb
<div class="row <%= 'top-row' if top_row %>">
  <div class="three columns pull-right">
    <div class="cart-total" <% if cart.empty? %> style="display: none;" <% end %>>
      <h5>Total: <span class="price">$<%= cart.total_price %></span></h5>
      <%= link_to 'Checkout', skip_measurements ? new_order_path : measurements_path, class: 'button full-width large' %>
    </div>
  </div>
</div>

app/views/carts/_customization_list.html.erb
<div class="four columns">
  <ul>
    <% customizations.each do |customization| %>
      <li>
        <a href="#" class="edit-customization-option" data-type="<%= customization_to_key(customization[:option]) %>">
          <span class="label"><%= customization[:option] %></span>: <%= customization[:type] %>
        </a>
      </li>
    <% end %>
  </ul>
</div>

app/views/carts/show.html.erb
<% title_helper('Shopping Cart') %>

<div class="content-wrapper">
  <h1>Shopping Cart</h1>
  <%= render('checkout', cart: @cart, skip_measurements: @skip_measurements, top_row: true) if @cart.num_items > 1 %>
  <%= render @cart.line_items %>
  <div class="empty-cart" <% unless @cart.empty? %> style="display: none;" <% end %>>
    <p>You haven't added anything to your cart yet.</p>
    <a href="/shop" class="button">Go To Shop</a>
  </div>
  <%= render 'checkout', cart: @cart, skip_measurements: @skip_measurements, top_row: false %>
</div>

<script>
  $(function() {
    new TR.Views.Cart({lineItems: <%= @line_items.to_json.html_safe %>});
  });
</script>

<%= render 'shared/customization_data' %>