config/routes.rb
TailoredRepublic::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

  devise_for :users, skip: [:sessions, :registrations],
             controllers: { sessions: :sessions, registrations: :registrations }
  as :user do
    get 'login' => 'sessions#new', :as => :new_user_session
    post 'login' => 'sessions#create', :as => :user_session
    delete 'sign-out' => 'sessions#destroy', :as => :destroy_user_session
    post 'account' => 'registrations#create', :as => :user_registration
    put 'account' => 'registrations#update'
    delete 'account' => 'devise/registrations#destroy'
    get 'account' => 'registrations#edit', :as => :edit_user_registration
  end

  resources :users, only: [:show, :update, :destroy, :index, :edit], path: '/admin/users'
  resources :customizations, only: [:show, :create, :update]
  resource  :cart, only: [:show]
  resource  :measurements, only: [:show, :create, :update]
  resources :products, only: [:show, :index, :create, :update] do
    resources :reviews, only: [:new, :edit] do
      collection do
        get 'paginated'
      end
    end
  end
  resources :products, only: [:new, :edit, :admin_index], path: '/admin/products' do
    collection do
      get 'index', action: 'admin_index'
    end
  end
  resources :coupons, except: [:show], path: '/admin/coupons' do
    collection do
      get 'help'
    end
  end
  resources :line_items, path: '/line-items', only: [:create, :destroy, :update]
  resources :tape_measure_requests, only: [:index, :update], path: '/admin/tape-measure-requests'
  resources :tape_measure_requests, only: [:new, :create], path: '/tape-measure-requests' do
    collection do
      get 'thank_you', path: 'thank-you'
    end
  end
  resources :orders, only: [:admin_index, :show], path: '/admin/orders' do
    collection do
      get 'index', action: 'admin_index'
    end
  end
  resources :orders, only: [:new, :create, :index] do
    collection do
      post 'review'
      post 'new', path: 'new'
      get 'thank_you', path: 'thank-you'
    end
  end
  resources :referrals, only: [:index] do
    collection do
      get 'invite/:referral_code', :action => 'invite'
      post 'email-friends', :action => 'email_friends'
    end
  end
  resources :reviews, only: [:update, :create, :index]
  resources :reviews, only: [:admin_index], path: '/admin/reviews' do
    collection do
      get 'index', action: 'admin_index'
    end
  end
  resources :testimonials, only: [:index, :update, :create]
  resources :testimonials, except: [:index, :update, :create], path: '/admin/testimonials' do
    collection do
      get 'index', action: 'admin_index'
    end
  end

  match '/shop/:category' => 'shop#index'
  match '/shop/:category/:subcategory' => 'shop#index'
  match '/gift-cards' => 'shop#gift_cards', :as => 'gift_cards'
  match '/shop' => 'shop#index'
  match '/home' => 'home#index'
  match '/measurements/:initial_slide' => 'measurements#show'
  match '/subscribe-to-newsletter' => 'mailing_list#subscribe', :as => 'subscribe_to_newsletter'
  match '/about' => 'pages#about'
  match '/admin' => 'pages#admin'
  match '/faq' => 'pages#faq'
  match '/graduation-1' => 'pages#graduation_with_clickable_product'
  match '/graduation-2' => 'pages#graduation_without_clickable_product'
  match '/lookbook' => 'pages#lookbook'
  match '/partners' => 'pages#partners'
  match '/press' => 'pages#press'
  match '/privacy-policy' => 'pages#privacy_policy'
  match '/process' => 'pages#process'
  match '/team' => 'pages#team'
  match '/terms-of-service' => 'pages#terms_of_service'
  match '/weddings' => 'pages#weddings'
  match '/top-picks' => 'pages#top_picks'

end

app/models/product.rb
require 'enumerated_attribute'

class Product < ActiveRecord::Base
  enum_attr :category, %w(suit shirt accessory gift_card)
  attr_accessible :description, :name, :price, :quantity, :category, :summary, :display_order, :top_pick, :subcategory,
                  :fabric_id, :product_photos_attributes

  has_many :line_items
  has_many :customizations
  has_many :reviews
  has_many :product_photos, order: 'default_photo DESC, created_at ASC', dependent: :destroy
  has_many :coupons, foreign_key: 'apply_to_product_id', class_name: 'Coupon'

  accepts_nested_attributes_for :product_photos, allow_destroy: true

  before_destroy :ensure_not_referenced_by_line_item

  extend FriendlyId
  friendly_id :name, use: :slugged

  def self.vest_price
    79
  end

  def self.pick_stitching_price
    10
  end

  def self.shirt_monogram_price
    5
  end

  def self.depluralize_category(category)
    case category
      when 'suits'
        :suit
      when 'shirts'
        :shirt
      when 'pants'
        :pants
      when 'accessories'
        :accessory
      else
        :error
    end
  end

  def self.top_picks
    self.where(top_pick: true).order('display_order ASC').limit(4)
  end

  def self.suggested(product_id)
    product = Product.find(product_id)
    suggested = []
    case product.category
      when :suit
        suggested << Product.random_by_category(:accessory)
        suggested << Product.random_by_category(:shirt)
      when :shirt
        suggested << Product.random_by_category(:accessory)
        suggested << Product.random_by_category(:suit)
      when :accessory
        suggested << Product.random_by_category(:suit)
        suggested << Product.random_by_category(:shirt)
      else
        suggested << Product.random_by_category(:shirt)
        suggested << Product.random_by_category(:suit)
    end
    suggested.flatten
  end

  def self.random_by_category(category)
    # Exclude Build Your Own Suit as a suggested product
    Product.where('category = ? AND name != ?', category, 'Build Your Own Suit').shuffle[0,2]
  end

  def as_json(options = {})
    json = super(options)
    json[:product_photos] = product_photos.map do |photo|
      {
        id: photo.id,
        original: photo.photo.url(:original),
        medium: photo.photo.url(:medium),
        small: photo.photo.url(:small),
        default_photo: photo.default_photo
      }
    end
    json
  end

  def self.by_category_and_subcategory(category, subcategory)
    query = where(category: category)
    query = query.where(subcategory: subcategory) if subcategory
    query.order('display_order ASC, subcategory ASC, name ASC').includes(:product_photos).to_a
  end

  def self.subcategories_for_category(category)
    Product.where(category: category).select(:subcategory).uniq.map { |p| p.subcategory }
  end

  def display_price
    price.to_i
  end

  def default_photo
    product_photos.find_by_default_photo(true)
  end

  def customizable?
    category == :suit || category == :shirt
  end

  def to_s
    name
  end

  def paginated_reviews(page = 1)
    reviews.accepted.includes(:user).paginate(page: page, per_page: 5).order('created_at DESC')
  end

  def average_rating
    accepted_reviews = reviews.accepted
    if accepted_reviews.length > 0
      (accepted_reviews.average('rating') * 2).round / 2.0 # Round to nearest 0.5
    else
      0
    end
  end

  private
    def ensure_not_referenced_by_line_item
      if line_items.empty?
        true
      else
        errors.add :base, 'Cart items present'
        false
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource except: [:show, :index]

  def index
    if params[:suggested]
      @products = Product.suggested(params[:product_id]).to_json(include: [:product_photos])
    else
      @products = Product.includes(:product_photos).order('category ASC, name ASC').all
    end

    respond_to do |format|
      format.json { render json: @products }
    end
  end

  def admin_index
    @products = Product.order('category ASC, name ASC').all
  end

  def show
    @product = Product.find(params[:id]) || (render_404 and return)
    @category = @product.category.to_s.pluralize
    @reviews = @product.paginated_reviews

    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

  def new
    @product = Product.new
    5.times { @product.product_photos.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  def edit
    @product = Product.find(params[:id])
    5.times { @product.product_photos.build }
  end

  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to 'admin/products', notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to edit_product_path(@product), notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/views/products/_form.html.erb
<%= form_for @product, html: { class: 'outlined' } do |f| %>
  <%= render 'shared/form_errors', resource: @product %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :category %>
  <%= f.enum_select :category %>
  <%= f.label :subcategory %>
  <%= f.text_field :subcategory %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :summary %>
  <%= f.text_field :summary %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.label :fabric_id %>
  <%= f.text_field :fabric_id %>
  <%= f.label :display_order %>
  <%= f.text_field :display_order %>
  <%= f.radio_button :top_pick, "true" %>
  <%= f.label 'Top Pick (yes)' %>
  <%= f.radio_button :top_pick, "false" %>
  <%= f.label 'Top Pick (no)' %>
  <%= f.label 'New Photos' %>
  <%= f.fields_for :product_photos do |photo| %>
    <div>
      <% if photo.object.new_record? %>
        <%= photo.file_field :photo %>
      <% end %>
    </div>
  <% end %>
  <%= f.label 'Existing Photos' %>
  <ul>
    <%= f.fields_for :product_photos do |photo| %>
      <% unless photo.object.new_record? %>
        <li class="thumbnail outlined">
          <p><%= photo.object.photo_file_name %></p>
          <%= link_to(image_tag(photo.object.photo.url(:small)), photo.object.photo.url(:original)) %>
          <label>Default photo <%= photo.check_box :default_photo, class: 'default-photo-checkbox' %></label>
          <label>Delete? <%= photo.check_box :_destroy %></label>
        </li>
      <% end %>
    <% end %>
  </ul>
  <%= f.submit class: "button" %>
<% end %>

<script>
  $(function() {
    $('.default-photo-checkbox').on('click', function(e) {
      $('.default-photo-checkbox:checked').removeAttr('checked');
      $(this).prop('checked', true)
    });
  });
</script>

app/views/products/_product.html.erb
<div class="product-wrapper three columns" data-id="<%= product.id %>">
  <%= link_to(image_tag(product.default_photo.photo.url(:medium)), product) if product.default_photo %>
  <div class="product-info-wrapper">
    <div class="product-info">
      <div class="product-name">
        <%= link_to product do %>
          <%= product.name %> <span class="divider">//</span> <span class="dollar">$</span><%= product.display_price %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/_products.html.erb
<% products.each_slice(4) do |a, b, c, d| %>
  <div class="products-wrapper">
    <%= render 'products/product', product: a if a %>
    <%= render 'products/product', product: b if b %>
    <%= render 'products/product', product: c if c %>
    <%= render 'products/product', product: d if d %>
  </div>
<% end %>

app/views/products/admin_index.erb
<div class="twelve columns">
  <h2>Products</h2>
  <div class="outlined">

    <p id="notice"><%= notice %></p>

    <%= link_to 'New Product', new_product_path, class: "button" %>
    <table>
      <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Subcategory</th>
        <th>Description</th>
        <th>Summary</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Display Order</th>
        <th>Fabric ID</th>
        <th>Top Pick?</th>
        <th></th>
        <th></th>
      </tr>

      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.category %></td>
          <td><%= product.subcategory %></td>
          <td><%= product.description %></td>
          <td><%= product.summary %></td>
          <td><%= number_to_currency product.price %></td>
          <td><%= product.quantity %></td>
          <td><%= product.display_order %></td>
          <td><%= product.fabric_id %></td>
          <td><%= product.top_pick ? 'Yes' : 'No' %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>

  </div>

</div>

app/views/products/admin_index.html.erb
<div class="twelve columns">
  <h2>Products</h2>
  <div class="outlined">

    <p id="notice"><%= notice %></p>

    <%= link_to 'New Product', new_product_path, class: "button" %>
    <table>
      <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Subcategory</th>
        <th>Description</th>
        <th>Summary</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Display Order</th>
        <th>Fabric ID</th>
        <th>Top Pick?</th>
        <th></th>
        <th></th>
      </tr>

      <% @products.each do |product| %>
        <tr>
          <td><%= link_to product.name, product %></td>
          <td><%= product.category %></td>
          <td><%= product.subcategory %></td>
          <td><%= product.description %></td>
          <td><%= product.summary %></td>
          <td><%= number_to_currency product.price %></td>
          <td><%= product.quantity %></td>
          <td><%= product.display_order %></td>
          <td><%= product.fabric_id %></td>
          <td><%= product.top_pick ? 'Yes' : 'No' %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>

  </div>

</div>

app/views/products/edit.html.erb
<div class="twelve columns content-wrapper">
  <h2>Editing product</h2>
  <%= render 'form' %>

  <%= link_to 'Show', @product %> |
  <%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<div class="twelve columns">
  <h2>Products</h2>
  <div class="outlined">

    <p id="notice"><%= notice %></p>

    <%= link_to 'New Product', new_product_path, class: "button" %>
    <table>
      <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Subcategory</th>
        <th>Description</th>
        <th>Summary</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Display Order</th>
        <th>Fabric ID</th>
        <th>Top Pick?</th>
        <th></th>
        <th></th>
      </tr>

      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.category %></td>
          <td><%= product.subcategory %></td>
          <td><%= product.description %></td>
          <td><%= product.summary %></td>
          <td><%= number_to_currency product.price %></td>
          <td><%= product.quantity %></td>
          <td><%= product.display_order %></td>
          <td><%= product.fabric_id %></td>
          <td><%= product.top_pick ? 'Yes' : 'No' %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>

  </div>

</div>

app/views/products/new.html.erb
<div class="row content-wrapper">
  <div class="twelve columns">
    <h2>New product</h2>
    <%= render 'form' %>
    <%= link_to 'Back', products_path %>
  </div>
</div>

app/views/products/show.html.erb
<%= title_helper @product.name %>
<%= content_for :description, @product.description %>

<div class="content-wrapper">
  <div class="dashed-bottom">
    <%= link_to "Back To #{@category.capitalize}", "/shop/#@category", class: 'button pull-left' %>
    <% unless @cart.empty? %>
      <%= link_to "View Cart", "/cart", class: 'button pull-right' %>
    <% end %>
  </div>
  <h2><%= @product.name %><span class="divider">&nbsp;//&nbsp;</span>$<%= @product.display_price %></h2>
  <div class="row dashed-bottom product-row">
    <div class="five columns preview-wrapper">
      <ul class="thumbnail-list three columns">
        <% @product.product_photos.each do |photo| %>
          <li><%= link_to image_tag(photo.photo.url(:small)), '#', data: { id: photo.id }, class: 'switch-image' %></li>
        <% end %>
      </ul>
      <div class="magnify nine columns">
        <%= image_tag @product.default_photo.photo.url(:medium), class: 'magnify-small' unless @product.default_photo.nil? %>
        <p>Hover to magnify</p>
      </div>
    </div>
    <div class="seven columns outlined">
      <div class="image-magnified" style="display: none;">
        <%= image_tag @product.default_photo.photo.url(:original), class: 'magnify-large' unless @product.default_photo.nil? %>
      </div>
      <div class="product-summary">
        <h4><%= @product.summary %></h4>
        <p class="blurb"><%= @product.description %></p>
        <% if @product.customizable? %>
          <%= link_to 'Customize', '#', class: 'customize button large full-width' %>
        <% else %>
          <%= link_to 'Add to Cart', '#', class: 'add-to-cart-no-customization button large full-width' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <h3>Reviews</h3>
    <div class="twelve columns outlined">
      <% if user_signed_in? %>
        <% if current_user.can_review_product?(@product) %>
          <%= link_to 'Add Review', new_product_review_path(@product), class: 'button margin-bottom' %>
        <% else %>
          <p>You have already submitted a review for this product.
            <%= link_to 'Edit your review.', edit_product_review_path(@product, current_user.find_review_by_product(@product)) %></p>
        <% end %>
      <% else %>
        <p><%= link_to 'Login or sign up', new_user_session_path %> to add a new review for this product.</p>
      <% end %>
      <% if @reviews.length > 0 %>
        <h4>Overall Rating <%= render 'reviews/stars', editable: false, num_stars: @product.average_rating %></h4>
        <%= render 'reviews/review_list', reviews: @reviews %>
      <% else %>
        <p>No reviews have been added for this product yet.</p>
      <% end %>
    </div>
  </div>
</div>

<script>
  var product = new TR.Models.Product(<%= @product.to_json.html_safe %>);
  var paginatedReviewPath = '<%= paginated_product_reviews_path(@product) %>';
  new TR.Views.Product({model: product, paginatedReviewPath: paginatedReviewPath});
</script>

<%= render 'shared/customization_data' %>