config/routes.rb
TailoredRepublic::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

  devise_for :users, skip: [:sessions, :registrations],
             controllers: { sessions: :sessions, registrations: :registrations }
  as :user do
    get 'login' => 'sessions#new', :as => :new_user_session
    post 'login' => 'sessions#create', :as => :user_session
    delete 'sign-out' => 'sessions#destroy', :as => :destroy_user_session
    post 'account' => 'registrations#create', :as => :user_registration
    put 'account' => 'registrations#update'
    delete 'account' => 'devise/registrations#destroy'
    get 'account' => 'registrations#edit', :as => :edit_user_registration
  end

  resources :users, only: [:show, :update, :destroy, :index, :edit], path: '/admin/users'
  resources :customizations, only: [:show, :create, :update]
  resource  :cart, only: [:show]
  resource  :measurements, only: [:show, :create, :update]
  resources :products, only: [:show, :index, :create, :update] do
    resources :reviews, only: [:new, :edit] do
      collection do
        get 'paginated'
      end
    end
  end
  resources :products, only: [:new, :edit, :admin_index], path: '/admin/products' do
    collection do
      get 'index', action: 'admin_index'
    end
  end
  resources :coupons, except: [:show], path: '/admin/coupons' do
    collection do
      get 'help'
    end
  end
  resources :line_items, path: '/line-items', only: [:create, :destroy, :update]
  resources :tape_measure_requests, only: [:index, :update], path: '/admin/tape-measure-requests'
  resources :tape_measure_requests, only: [:new, :create], path: '/tape-measure-requests' do
    collection do
      get 'thank_you', path: 'thank-you'
    end
  end
  resources :orders, only: [:admin_index, :show], path: '/admin/orders' do
    collection do
      get 'index', action: 'admin_index'
    end
  end
  resources :orders, only: [:new, :create, :index] do
    collection do
      post 'review'
      post 'new', path: 'new'
      get 'thank_you', path: 'thank-you'
    end
  end
  resources :referrals, only: [:index] do
    collection do
      get 'invite/:referral_code', :action => 'invite'
      post 'email-friends', :action => 'email_friends'
    end
  end
  resources :reviews, only: [:update, :create, :index]
  resources :reviews, only: [:admin_index], path: '/admin/reviews' do
    collection do
      get 'index', action: 'admin_index'
    end
  end
  resources :testimonials, only: [:index, :update, :create]
  resources :testimonials, except: [:index, :update, :create], path: '/admin/testimonials' do
    collection do
      get 'index', action: 'admin_index'
    end
  end

  match '/shop/:category' => 'shop#index'
  match '/shop/:category/:subcategory' => 'shop#index'
  match '/gift-cards' => 'shop#gift_cards', :as => 'gift_cards'
  match '/shop' => 'shop#index'
  match '/home' => 'home#index'
  match '/measurements/:initial_slide' => 'measurements#show'
  match '/subscribe-to-newsletter' => 'mailing_list#subscribe', :as => 'subscribe_to_newsletter'
  match '/about' => 'pages#about'
  match '/admin' => 'pages#admin'
  match '/faq' => 'pages#faq'
  match '/graduation-1' => 'pages#graduation_with_clickable_product'
  match '/graduation-2' => 'pages#graduation_without_clickable_product'
  match '/lookbook' => 'pages#lookbook'
  match '/partners' => 'pages#partners'
  match '/press' => 'pages#press'
  match '/privacy-policy' => 'pages#privacy_policy'
  match '/process' => 'pages#process'
  match '/team' => 'pages#team'
  match '/terms-of-service' => 'pages#terms_of_service'
  match '/weddings' => 'pages#weddings'
  match '/top-picks' => 'pages#top_picks'

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  attr_accessible :photo, :caption, :social_handle, :social_url

  default_scope order('created_at DESC')

  has_attached_file :photo, path: '/testimonials/:style/:basename.:extension',
                    styles: { medium: '300x', small: '100x' }
  validates_attachment_presence :photo
  validates_attachment_size :photo, less_than: 5.megabytes
  validates_attachment_content_type :photo, content_type: ['image/jpeg', 'image/png']
  validates :caption,  length: { minimum: 1, maximum: 200 }

  self.per_page = 20

  def has_social?
    !social_handle.nil? && !social_url.nil?
  end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  load_and_authorize_resource except: [:index]

  def index
    @testimonials = Testimonial.paginate(page: params[:page] ||= 1, per_page: 15)
  end

  def admin_index
    @testimonials = Testimonial.paginate(page: params[:page] ||= 1)
  end

  def new
    @testimonial = Testimonial.new
  end

  def edit
    @testimonial = Testimonial.find(params[:id])
  end

  def create
    @testimonial = Testimonial.new(params[:testimonial])

    if @testimonial.save
      redirect_to '/admin/testimonials', notice: 'Testimonial successfully added.'
    else
      render :new
    end
  end

  def update
    @testimonial = Testimonial.find(params[:id])

    if @testimonial.update_attributes(params[:testimonial])
      redirect_to '/admin/testimonials', notice: 'Testimonial successfully updated.'
    else
      render :edit
    end
  end
end

app/views/testimonials/_form.html.erb
<%= form_for @testimonial, html: { class: 'outlined' } do |f| %>
  <%= render 'shared/form_errors', resource: @testimonial %>
  <% if @testimonial.photo.file? %>
    <%= image_tag @testimonial.photo.url(:medium) %>
  <% end %>
  <%= f.label :photo %>
  <%= f.file_field :photo %>
  <%= f.label :caption %>
  <%= f.text_field :caption %>
  <%= f.label :social_handle, 'Social media handle (Twitter, Facebook, Instagram, etc. name)' %>
  <%= f.text_field :social_handle %>
  <%= f.label :social_url, 'Social URL (Link to above user\'s page)' %>
  <%= f.text_field :social_url %>
  <%= f.submit class: "button" %>
<% end %>

app/views/testimonials/_testimonials.html.erb
<div class="testimonials-row">
  <% testimonials.even_groups_of(3).each do |group| %>
    <div class="four columns">
      <% group.each do |testimonial| %>
        <% if testimonial.photo.file? %>
          <div class="testimonial">
            <%= image_tag testimonial.photo.url(:medium) %>
            <p>
              <%= testimonial.caption %><br/>
              <%= link_to "@#{testimonial.social_handle}", testimonial.social_url if testimonial.has_social? %>
            </p>
        <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<% if should_paginate %>
  <div class="twelve columns">
    <%= will_paginate testimonials %>
  </div>
<% end %>

app/views/testimonials/admin_index.html.erb
<div class="twelve columns">
  <h2>Testimonials</h2>

  <%= link_to 'New testimonial', new_testimonial_path, class: 'button margin-bottom' %>
  <div class="outlined">
    <table>
      <tr>
        <th>Photo</th>
        <th>Caption</th>
        <th>Social handle</th>
        <th>Social URL</th>
        <th>Date Created</th>
        <th></th>
        <th></th>
      </tr>

      <% @testimonials.each do |testimonial| %>
        <tr>
          <td><%= image_tag testimonial.photo.url(:small) %></td>
          <td><%= testimonial.caption %></td>
          <td><%= testimonial.social_handle %></td>
          <td><%= link_to testimonial.social_url, testimonial.social_url, target: '_blank' %></td>
          <td><%= testimonial.created_at_friendly(pacific: true) %></td>
          <td><%= link_to 'Edit', edit_testimonial_path(testimonial) %></td>
          <td><%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>

    <%= will_paginate @testimonials %>
  </div>
</div>

app/views/testimonials/edit.html.erb
<div class="row content-wrapper">
  <div class="twelve columns">
    <h2>Edit Testimonial</h2>
    <%= render 'form' %>
    <%= link_to 'Back to Testimonials', '/admin/testimonials', class: 'button margin-bottom' %>
  </div>
</div>

app/views/testimonials/index.html.erb
<div class="row content-wrapper">
  <div class="twelve columns">
    <h2>Customer Testimonials</h2>
  </div>
  <%= render 'testimonials/testimonials', testimonials: @testimonials, should_paginate: true %>
</div>

<script>
  new TR.Views.Testimonials();
</script>

app/views/testimonials/new.html.erb
<div class="row content-wrapper">
  <div class="twelve columns">
    <h2>New Testimonial</h2>
    <%= render 'form' %>
    <%= link_to 'Back to Testimonials', '/admin/testimonials', class: 'button margin-bottom' %>
  </div>
</div>